spring.application.name=tandapp
spring.datasource.url=jdbc:postgresql://localhost:5432/tandapp
spring.datasource.username=tandapp
spring.datasource.password=tandapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.clean-disabled=false

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=esta_es_una_clave_muy_secreta_y_larga_de_32_caracteres
jwt.expiration=900000

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG