spring.application.name=authServiceT
spring.datasource.url=jdbc:postgresql://localhost:5432/authServiceT
spring.datasource.username=authServiceT
spring.datasource.password=authServiceT
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.clean-disabled=false

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

jwt.secret=esta_es_una_clave_secreta_super_larga_32_chars
jwt.expiration=900000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG