name: JAVA CI with Maven

on:
  push:
    tags: 'v*'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo 💻
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Upload Artifact 📦
        uses: actions/upload-artifact@v4
        with:
          name: tandapp-auth-service
          path: target/*.jar

      - name: Start testing process
        run: mvn clean test

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tandapp-auth-service

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./*.jar
          body: "New steady version generated by Git Tag."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: release
    if: always() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Cloning repo 💻
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete Merged Branches 🧹
        run: |
          git fetch --prune
          for branch in $(git branch -r --merged origin/main | grep -v 'origin/main' | sed 's/origin\///'); do
            git push origin --delete $branch || echo "$branch cannot be deleted"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


